name: Inspect

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Init Stuff
      uses: ./.github/actions/init
    - name: Build
      run: pnpm build
    - name: Upload Builds
      uses: actions/upload-pages-artifact@v2
      with:
        path: dist

  pages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
    - build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
