name: Inspect

on: push

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Init Stuff
      uses: ./.github/actions/init
    - name: Build
      run: yarn build
    - name: Upload Builds
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          dist/

  gh-pages:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
    - build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Init Stuff
      uses: ./.github/actions/init
    - name: Download Builds
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
